Feature/customers review
SmukuHapace/icecream-project pull request #14
Opened 2023-01-29 14:21 UTC by Bartosz-Zarski

2023-01-30 14:53 UTC, SmukuHapace requested changes

2023-01-30 14:53 UTC, SmukuHapace commented on src/partials/customer-reviews.html
> +            </svg>
??

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +    border-radius: 50%;
nie potrzebne, zdj już są okrągłe

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +    font-family: 'DM Sans';
użyj mixin

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +      font-family: inherit;
nie potrzebne? ten znak raczej nie wykorzystuje family

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +    margin: 14px auto 18px auto;
można zrobić to prościej `margin: 14px auto 18px;`

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +    font-family: inherit;
mixin

2023-01-30 14:53 UTC, SmukuHapace commented on src/sass/components/_customer-reviews.scss
> +      margin: 16px auto 9px auto;
można `margin: 16px auto 9px;`

2023-01-31 12:55 UTC, Bartosz-Zarski commented
Tutaj nie kumam o co chodzi. Samanta poprawiała pliczek z ikonami, ale ja też zrobiłem go dokładnie tak jak ona ma i wywala konflikt.

2023-01-31 21:15 UTC, SmukuHapace approved these changes

2023-01-31 21:16 UTC, merged